version: '2'

volumes:
  postgres_data: {}
  postgres_backup: {}
  caddy: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app
      - ./data/media:/app/media
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=gtgs
      - USE_DOCKER=yes
      - EMAIL_DESTINATION=equipe@scielo.org
      - DJANGO_ACCOUNT_ALLOW_REGISTRATION=True
      - DJANGO_ALLOWED_HOSTS=*
      - DJANGO_DEBUG=False
      - DJANGO_DEFAULT_FROM_EMAIL=scielo.aplicacao@scielo.org
#      - DJANGO_EMAIL_HOST=mailserver.foobar.scielo.org
#      - DJANGO_EMAIL_HOST_PASSWORD=foobarbaz1234
#      - DJANGO_EMAIL_HOST_USER=foobar
#      - DJANGO_EMAIL_PORT=1234
      - DJANGO_EMAIL_SUBJECT_PREFIX=[\o/]
      - DJANGO_EMAIL_USE_SSL=False
      - DJANGO_EMAIL_USE_TLS=True
      - DJANGO_SECRET_KEY=very-secret-secret
      - DJANGO_SECURE_SSL_REDIRECT=False
      - DJANGO_SETTINGS_MODULE=config.settings.production
    command: /gunicorn.sh

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_backup:/backups
    environment:
      - POSTGRES_USER=gtgs

  caddy:
    build:
      context: .
      dockerfile: ./compose/production/caddy/Dockerfile
    depends_on:
      - django
    volumes:
      - caddy:/root/.caddy
    env_file: .env
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"

  redis:
    image: redis:3.0

  celeryworker:
    <<: *django
    depends_on:
     - postgres
     - redis
    command: /start-celeryworker.sh

  celerybeat:
    <<: *django
    depends_on:
      - postgres
      - redis
    command: /start-celerybeat.sh

