# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-23 11:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='anniversary',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data de admissão (DD/MM/AAAA)'),
        ),
        migrations.AddField(
            model_name='user',
            name='birthdate',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Birthdate (DD/MM/AAAA)'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_checked',
            field=models.BooleanField(default=False, verbose_name='Data is checked'),
        ),
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='/app/gtgs/media/photo.png', upload_to='', verbose_name='Photo'),
        ),
    ]
