# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-04 18:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20171201_1517'),
        ('users', '0002_auto_20171204_1549'),
    ]

    operations = [
    ]
