# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-23 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20171123_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_checked_by_admin',
            field=models.BooleanField(default=False, verbose_name='Confirmo que os dados do usuário estão atualizados'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_checked',
            field=models.BooleanField(default=False, verbose_name='Confirmo que meus dados estão atualizados'),
        ),
    ]
