# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-29 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20171123_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='anniversary_alert',
            field=models.BooleanField(default=True, verbose_name='Alertar aniversário'),
        ),
        migrations.AddField(
            model_name='user',
            name='birthdate_alert',
            field=models.BooleanField(default=True, verbose_name='Alertar tempo de SciELO'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_checked',
            field=models.BooleanField(default=False, verbose_name='Confirmo que estes dados estão atualizados'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_checked_by_admin',
            field=models.BooleanField(default=False, verbose_name='Validado'),
        ),
    ]
