# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-29 16:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20171129_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='anniversary_alert',
            field=models.BooleanField(default=True, verbose_name='Alertar tempo de SciELO'),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthdate',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data de nascimento (DD/MM/AAAA)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthdate_alert',
            field=models.BooleanField(default=True, verbose_name='Alertar aniversário'),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='/app/gtgs/media/perfil.png', upload_to='', verbose_name='Photo'),
        ),
    ]
